services:
  # ...

  Palmyr\SymfonyAws\Command\GetCallerIdentityCommand:
    class: Palmyr\SymfonyAws\Command\GetCallerIdentityCommand
    arguments:
      - '@Aws\Sts\StsClient'
    tags:
      - name: 'console.command'