services:
  # ...

  Palmyr\SymfonyAws\Command\GetCallerIdentityCommand:
    class: Palmyr\SymfonyAws\Command\GetCallerIdentityCommand
    tags:
      - name: 'console.command'
      - name: 'container.service_subscriber'