services:

  Palmyr\SymfonyAws\Service\AwsIniFileServiceInterface:
    class: Palmyr\SymfonyAws\Service\AwsIniFileService

  Palmyr\SymfonyAws\Factory\SdkFactoryInterface:
    class: Palmyr\SymfonyAws\Factory\SdkFactory
    arguments:
      - '@property_accessor'
      - '@Palmyr\SymfonyAws\Service\AwsIniFileServiceInterface'

  Aws\Sdk:
    class: Aws\Sdk
    arguments:
      - '%palmyr.aws.sdk.options%'
    factory:
      - '@Palmyr\SymfonyAws\Factory\SdkFactoryInterface'
      - 'build'

  Aws\Sts\StsClient:
    class: Aws\Sts\StsClient
    factory:
      - '@Aws\Sdk'
      - 'createSts'

